export const CREATE_TIMER = {
    OPEN: 'CREATE_TIMER.OPEN',
    CHANGE: 'CREATE_TIMER.CHANGE',
    CLOSE: 'CREATE_TIMER.CLOSE',
    REGISTER: 'CREATE_TIMER.REGISTER'
};
export const GAME_TIMER = {
    LOAD: 'GAME_TIMER.LOAD',
    DELETE: 'GAME_TIMER.DELETE',
    SHOW_DRAWER: 'GAME_TIMER.SHOW_DRAWER',
    HIDE_DRAWER: 'GAME_TIMER.HIDE_DRAWER',
    UPDATE_APP: 'GAME_TIMER.UPDATE_APP'
}