export const CREATE_TIMER = {
    OPEN: 'CREATE_TIMER.OPEN',
    CHANGE: 'CREATE_TIMER.CHANGE',
    CLOSE: 'CREATE_TIMER.CLOSE',
    REGISTER: 'CREATE_TIMER.REGISTER'
};
export const GAME_TIMER = {
    LOAD: 'GAME_TIMER.LOAD',
    DELETE: 'GAME_TIMER.DELETE',
    REGISTER_TIMER: 'GAME_TIMER.REGISTER_TIMER',
    DELETE_TIMER: 'GAME_TIMER.DELETE_TIMER',
    ADD_TIMER_INSTANCE: 'GAME_TIMER.ADD_TIMER_INSTANCE',
    REMOVE_TIMER_INSTANCE: 'GAME_TIMER.REMOVE_TIMER_INSTANCE',
    SHOW_DRAWER: 'GAME_TIMER.SHOW_DRAWER',
    HIDE_DRAWER: 'GAME_TIMER.HIDE_DRAWER',
    UPDATE_APP: 'GAME_TIMER.UPDATE_APP',
    LOAD_AUDIO: 'GAME_TIMER.LOAD_AUDIO',
    START_TIMER: 'GAME_TIMER.START_TIMER',
    NOTIFY_TIMER: 'GAME_TIMER.NOTIFY_TIMER',
    STOP_RINGING: 'GAME_TIMER.STOP_RINGING'
}