export const CREATE_TIMER = {
    OPEN: 'CREATE_TIMER.OPEN',
    CHANGE: 'CREATE_TIMER.CHANGE',
    CLOSE: 'CREATE_TIMER.CLOSE',
    REGISTER: 'CREATE_TIMER.REGISTER'
};
export const GAME_TIMER = {
    LOAD: 'GAME_TIMER.LOAD'
}